### ISSUE TITLE
integration question

### ISSUE THREAD

**Issue by lcheng61** [LogicalSpark/openshift-solr-quickstart#3]
Hi, After installation, I can see the admin page on "http://solr-<domainname>.rhcloud.com/". However, I can't access "http://solr-<domainname>.rhcloud.com:8983" from outside. Can you please advise how to access solr gear service from outside ? What would be the port number to use ? Thanks,

**Comment by dameikle** [comment]
Hello,

Out-of-the box SOLR is accessible remotely on the standard HTTP port 80, so you can access the Admin page and the associated request handlers directly.

For example, using a fresh instance:

```
URL=http://<app>-<username>.rhcloud.com/collection1/update/json?commit=true
curl $URL -H 'Content-type:application/json' -d '
[
  {
    "id" : "1",
    "title" : "This is a test"
  }
]'
```

Would result in a document being posted into the standard schema the quick start ships with.

Cheers,
David

**Comment by lcheng61** [comment]
Thank you @dameikle. Do you know how to tell if the index is uploaded to solr ? I'm trying to connect from a gear installed with elgg_solr (https://elgg.org/plugins/1635100) to the gear installed with "solr". Would you suggest the setting I should input, based on the screen shot of elgg_solr plugin page ?

Besides the modifying schema api, is there any other unharmful api that I can list/show some item to prove the endpoint functional ?

**Comment by lcheng61** [comment]
@dameikle How can I remove the password of the http api access to Solr ? For example, I'm asked credential in the command below.

http://solr-lovebeautyapp.rhcloud.com/select/?q=video&indent=on&hl=true&hl.fl=name,features&facet=true&facet.field=cat&facet.mincount=1&wt=json

Thanks!

**Comment by lcheng61** [comment]
This is solved. Here is what I do:
1. Turn off solr authentication. Put solr behind a firewall
2. Use port 80
